In [1]:
import numpy as np

In [2]:
x = np.array([True, True, False, False, True, False, True])

In [3]:
x = x.reshape((1,len(x)))

In [5]:

x_repeated = np.repeat(x, 3, axis=0).T
x_repeated

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [False, False, False],
       [ True,  True,  True]])

In [6]:
x_repeated.shape

(7, 3)

In [7]:
x.shape

(1, 7)

In [8]:
N_overall = np.full((7,3), 0)

In [11]:
np.where(x_repeated, np.array([1,1,1]), N_overall)

array([[1, 1, 1],
       [1, 1, 1],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [0, 0, 0],
       [1, 1, 1]])

In [12]:
x1 = np.array([3, 8, 10, 0, 4])
x2 = np.array([3, 3, 3, 3, 3])

x1 < x2

array([False, False, False,  True, False])